name: Bash Project Tests
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y bash
      - name: insert +x to .bash_proile
        run: chmod +x ./.bash_profile
      - name: Run Tests
        run: |
          pwd
          ls -l
          if [ ! -f ./.bash_profile ]; then
            echo "Error: .bash_profile not found"
            exit 1
          fi
          OUTPUT=$(bash ./.bash_profile)
          echo "Script output:"
          echo "$OUTPUT"
          if [[ $OUTPUT =~ "Hello" ]]; then
            echo "Test 1: Passed"
          else
            echo "Error: 'Hello' not found in script output"
            exit 1
          fi
          echo "the test is work"
